master: 
  host: 10.2.0.47
  port: 3306
  username: yundamin
  password: tlRmfjdnj1
  database: yundamin18_godomall_com
slave1:
  host: 10.2.0.47
  port: 3306
  username: yundamin
  password: tlRmfjdnj1
  database: yundamin18_godomall_com
